[theme]
primaryColor = "#2a81c9"             # blue
backgroundColor = "#e6f0ff"          # very light blue
secondaryBackgroundColor = "#709255" # green
textColor = "#1f1f1f"                # dark gray/black text
font = "sans serif"